# -*- coding: utf-8 -*-
"""NLP UdeSA 2026. 09: Vector DB + LiteLLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t6M5e7bXA8sF6sc5Z_XkzHFl8w7Mm48c

# Vector DB + LiteLLM
## Materia: Procesamiento de Lenguaje Natural
### Maestría en en Ciencia de Datos
### UdeSA, 2026
### Profesor: Juan Manuel Pérez, Bruno Bianchi


Regístrense en [la página de Gemini/Google AI Studio y generen una API KEY](https://ai.google.dev/gemini-api/docs/api-key)

# ChromaDB + LiteLLM

Mini demo de cómo usar una base de datos vectorial (ChromaDB) y llamar a LLMs con LiteLLM.

## ChromaDB

ChromaDB es una base de datos vectorial. Permite guardar documentos, generar embeddings automáticamente, y hacer búsqueda por similitud.
"""

!pip install chromadb torchao==0.16.0

import chromadb

# Cliente en memoria (efímero) o persistente
# client = chromadb.Client()  # en memoria
client = chromadb.PersistentClient("./chroma")  # persistente en disco

# Crear una colección
collection = client.get_or_create_collection("demo")

textos = [
    "Python es un lenguaje de programación muy usado en aprendizaje supervisado.",
    "Vaaaaamooo boka",
    "A veces dos y dos son cinco.",
]

# Agregar documentos (ChromaDB genera embeddings automáticamente)
collection.add(
    ids=["1", "2", "3"],
    documents=textos,
)

print(f"Documentos en la colección: {collection.count()}")

# Buscar por similitud
query = "¿Qué herramientas se usan para machine learning?"

results = collection.query(
    query_texts=[query],
    n_results=2,
    include=["documents", "distances", "metadatas"],
)


print(results)

from transformers import AutoModel
import torch

model_name = "jinaai/jina-embeddings-v5-text-nano"
device = "cpu"
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
model = AutoModel.from_pretrained(
    model_name,
    trust_remote_code=True,
    dtype=torch.bfloat16,
).to(device=device)

"""## Ahora con embeddings"""

collection = client.get_or_create_collection("demo_embeddings")
embeddings = model.encode(textos, task="retrieval", prompt_name="document")


collection.add(
    ids=["1", "2", "3"],
    documents=textos,
    embeddings=embeddings.cpu().numpy()
)

# Buscar por similitud
query = "¿Qué herramientas se usan para machine learning?"
embedding = model.encode([query], task="retrieval", prompt_name="query")

results = collection.query(
    query_embeddings=embedding[0].cpu().numpy(),
    n_results=2,
    include=["documents", "distances", "metadatas"],
)


print(results)

"""## LiteLLM

LiteLLM unifica la interfaz para llamar a distintos LLMs (OpenAI, Gemini, Anthropic, etc.) con la misma API.
"""

from litellm import completion

# Requiere la API key como variable de entorno (GEMINI_API_KEY, OPENAI_API_KEY, etc.)
response = completion(
    model="gemini/gemini-3.1-flash-lite",
    messages=[{"role": "user", "content": "¿Qué es NLP? Respondé en una oración."}],
)

print(response.choices[0].message.content)

