[project]
name = "hotpot_qa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "chromadb>=1.5.8",
    "datasets>=3.6.0",
    "ipdb>=0.13.13",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "jupyter>=1.1.1",
    "langchain>=1.3.1",
    "litellm>=1.72.2",
    "peft>=0.19.1",
    "transformers[torch]>=5.0.0",
    "wikipedia>=1.4.0",
]

[dependency-groups]
dev = ["ipykernel>=7.2.0", "ipywidgets>=8.1.8", "jupyter>=1.1.1"]

# Esto hace que buildee el paquete (y se instale "hotpot_qa" dentro de `src/`)
[build-system]
requires = ["uv_build>=0.11.16,<0.12"]
build-backend = "uv_build"

[project.scripts]
ingest = "hotpot_qa.ingest:main"
answer_rag = "hotpot_qa.answer_rag:main"
